server:
  port: 8083


spring:
  application:
    name: notification-service

  #Mail Properties
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: a012dfe3b6b67a
    password: 4025ff77f8943e
  #Kafka consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
